services:
  api:
    image: ${IMAGE:?IMAGE is required}
    container_name: ranking-tenis-api
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3333"
    networks:
      - backend

networks:
  backend:
    external: true
    name: savaris_backend
